### ISSUE TITLE
Append/dynamic values?

### ISSUE THREAD

**Issue by Jonovono** [johnyorke/JYGraphView#3]
Hi. I was wondering if this is set up to handle dynamically adding data. I would like to add real time capabilities to it and wanted to check first if that's something included

Thanks!

**Comment by johnyorke** [comment]
I should really turn on notifications for open issues, shouldn't I?! 11 months on, here's my answer:

I don't think the current implementation would allow this. I'm re-writing the app that this class was born in, so at some point expect it to be superseded by a better, possibly Swift, incarnation that supports dynamic values. 

Apologies for my rather unhelpful and tardy response.
